// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageSettings } from "./ImageSettings";
import type { VideoSettings } from "./VideoSettings";

export type AppConfig = { imageSettings: ImageSettings, videoSettings: VideoSettings, };
