// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Corner } from "./Corner";

export type ImageSettings = { addLogo: boolean, clearFilesInputDirectory: boolean, clearFilesOutputDirectory: boolean, formatFavoriteList: Array<string>, format: string, inputDirectory: string, keepChildFoldersStructureInOutputDirectory: boolean, logoCorner: Corner, logoPath: string | null, logoScale: number, logoXOffsetScale: number, logoYOffsetScale: number, minPixelCount: number, outputDirectory: string, overwriteExistingFilesOutputDirectory: boolean, searchChildFolders: boolean, shouldConvertFormat: boolean, };
